# Generated by Django 5.0.7 on 2024-08-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_category_description_category_sub_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_title',
        ),
    ]
