# Generated by Django 5.0.7 on 2024-08-14 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_userprogress_chapter_userprogress_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('student', 'chapter')},
        ),
    ]
