# Generated by Django 5.0.7 on 2024-09-01 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_quizanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
