# Generated by Django 5.0.7 on 2024-09-02 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_user_activate_token_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activate_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
