# Generated by Django 5.0.7 on 2024-09-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_user_activate_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='interesting_cate',
        ),
    ]
