# Generated by Django 5.0.7 on 2024-09-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_student_rec_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interesting_cate',
            field=models.TextField(null=True),
        ),
    ]
